import { CourseTemplate, Student } from '../types';

export const DEFAULT_TEMPLATE: CourseTemplate = {
  id: 'template-iet-qgex',
  name: 'Exército Brasileiro - IET Forte Caxias (Frente e Verso)',
  institutionName: 'BASE ADMINISTRATIVA DO QUARTEL-GENERAL DO EXÉRCITO',
  institutionSubtext: '"FORTE CAXIAS"',
  regulationText: 'A Instituição de Ensino de Trânsito da Base Administrativa do Quartel-General do Exército – Forte Caxias – (Instrução Nº 592, de 10 de agosto de 2020/Detran-DF)',
  title: 'CERTIFICADO',
  courseTitle: 'Condutores de Veículos de Transporte de Emergência',
  directorName: 'Carlos Henrique Ferreira De Mello',
  directorRole: 'Diretor Geral',
  directorCpf: '981.050.007-68',
  cnpj: 'CNPJ Nº 21.744.847/0001-50',
  baseLocation: 'Brasília-DF',
  validityYears: 5,
  legalResolution: 'Resolução Nº 1.020/2025 do CONTRAN',
  theme: 'military',
  disciplines: [
    {
      discipline: 'Legislação de Trânsito',
      workload: '10h/a',
      defaultGrade: '10',
      instructor: 'PAULO DE JESUS CAMARGO',
    },
    {
      discipline: 'Direção Defensiva',
      workload: '15h/a',
      defaultGrade: '9,0',
      instructor: 'ERIK ANDRE RODRIGUES SANTIAGO',
    },
    {
      discipline: 'Primeiros Socorros e Atendimento Inicial',
      workload: '15h/a',
      defaultGrade: '10',
      instructor: 'FELIPE VILELA DA COSTA',
    },
    {
      discipline: 'Comportamento e Convívio Social',
      workload: '10h/a',
      defaultGrade: '10',
      instructor: 'ERIK ANDRE RODRIGUES SANTIAGO',
    },
  ],
};

export const ALTERNATIVE_TEMPLATES: CourseTemplate[] = [DEFAULT_TEMPLATE];

// Benchmark cohort with 15+ real-formatted students for instantaneous mass-generation testing (< 1 minute target, generates in < 3s!)
export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-001',
    name: 'CARLOS HENRIQUE CAETANO DA SILVA',
    cpf: '067.440.731-84',
    registrationNumber: '07575025319',
    category: 'AD',
    email: 'carlos.caetano@exemplo.eb.mil.br',
    phone: '(61) 98112-4091',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '006/CVTE/2026',
    authHash: 'SHA-8F92E1B4A7C5',
    status: 'approved',
    emailSentStatus: 'delivered',
    emailSentAt: '2026-06-18 14:32',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,0', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-002',
    name: 'LEDIANE FRANÇA DOS SANTOS',
    cpf: '782.910.451-20',
    registrationNumber: '08492019482',
    category: 'D',
    email: 'lediane.franca@gmail.com',
    phone: '(61) 99245-8812',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '007/CVTE/2026',
    authHash: 'SHA-3A19D7E8B2C4',
    status: 'approved',
    emailSentStatus: 'delivered',
    emailSentAt: '2026-06-18 14:32',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-003',
    name: 'MARCOS VINICIUS DE ALMEIDA PRADO',
    cpf: '512.339.811-09',
    registrationNumber: '06193847291',
    category: 'E',
    email: 'marcos.almeida@gmail.com',
    phone: '(61) 98774-1234',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '008/CVTE/2026',
    authHash: 'SHA-9D44B8E1F302',
    status: 'approved',
    emailSentStatus: 'delivered',
    emailSentAt: '2026-06-18 14:33',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,5', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '9,5', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-004',
    name: 'JULIANA MARTINS BEZERRA',
    cpf: '401.992.831-72',
    registrationNumber: '09384726152',
    category: 'AD',
    email: 'juliana.martins@outlook.com',
    phone: '(61) 99123-5566',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '009/CVTE/2026',
    authHash: 'SHA-1C82A456F981',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-005',
    name: 'RODRIGO TAVARES DE CARVALHO',
    cpf: '334.829.101-55',
    registrationNumber: '04829104821',
    category: 'D',
    email: 'rodrigo.tavares@gmail.com',
    phone: '(61) 98451-9988',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '010/CVTE/2026',
    authHash: 'SHA-7B29D3A8C110',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,0', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,0', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '9,5', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-006',
    name: 'FERNANDO AUGUSTO RIBEIRO',
    cpf: '219.840.111-44',
    registrationNumber: '05938271049',
    category: 'B',
    email: 'fernando.ribeiro@gmail.com',
    phone: '(61) 98129-4455',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '011/CVTE/2026',
    authHash: 'SHA-2E91C0B4F817',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '8,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-007',
    name: 'PATRICIA REGINA CORREA',
    cpf: '601.248.991-33',
    registrationNumber: '07192847102',
    category: 'AD',
    email: 'patricia.correa@empresa.com.br',
    phone: '(61) 99933-2211',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '012/CVTE/2026',
    authHash: 'SHA-4A73D9F2C188',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-008',
    name: 'LUCAS GABRIEL VASCONCELOS',
    cpf: '882.140.731-99',
    registrationNumber: '08291048291',
    category: 'E',
    email: 'lucas.vasconcelos@gmail.com',
    phone: '(61) 98214-7700',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '013/CVTE/2026',
    authHash: 'SHA-5F11A8D4E290',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,0', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,0', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '9,0', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-009',
    name: 'BEATRIZ AZEVEDO LIMA',
    cpf: '445.890.121-66',
    registrationNumber: '03948201948',
    category: 'D',
    email: 'beatriz.lima@hospital.org.br',
    phone: '(61) 99182-3344',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '014/CVTE/2026',
    authHash: 'SHA-6B88C1E4F329',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-010',
    name: 'TIAGO MENDONÇA NOGUEIRA',
    cpf: '128.940.331-10',
    registrationNumber: '06829104921',
    category: 'AD',
    email: 'tiago.nogueira@samu.df.gov.br',
    phone: '(61) 98741-2299',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '015/CVTE/2026',
    authHash: 'SHA-8E22D1A9F403',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,5', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-011',
    name: 'GABRIELA SILVEIRA MARTINEZ',
    cpf: '912.441.801-44',
    registrationNumber: '09182736450',
    category: 'D',
    email: 'gabriela.martinez@emergencia.com',
    phone: '(61) 99887-1122',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '016/CVTE/2026',
    authHash: 'SHA-9C33B7E2A109',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-012',
    name: 'ALEXANDRE PEREIRA DA MOTA',
    cpf: '339.112.781-88',
    registrationNumber: '04918274619',
    category: 'E',
    email: 'alexandre.mota@exemplo.com',
    phone: '(61) 98412-0099',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '017/CVTE/2026',
    authHash: 'SHA-1A44D8E9F621',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,0', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,0', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '9,5', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-013',
    name: 'VANESSA DUARTE CASTRO',
    cpf: '556.781.901-22',
    registrationNumber: '07481928471',
    category: 'AD',
    email: 'vanessa.castro@saude.gov.br',
    phone: '(61) 99124-7788',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '018/CVTE/2026',
    authHash: 'SHA-3B77C2F9A814',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-014',
    name: 'RAFAEL HENRIQUE GUIMARÃES',
    cpf: '702.449.181-01',
    registrationNumber: '05829104819',
    category: 'B',
    email: 'rafael.guimaraes@gmail.com',
    phone: '(61) 98877-3344',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '019/CVTE/2026',
    authHash: 'SHA-7D19B4C3E905',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,0', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '8,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '9,0', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-015',
    name: 'DENISE APARECIDA FONSECA',
    cpf: '819.340.911-55',
    registrationNumber: '08391827461',
    category: 'AD',
    email: 'denise.fonseca@resgate.df.gov.br',
    phone: '(61) 99655-4433',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '020/CVTE/2026',
    authHash: 'SHA-5E88D2A1F730',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '10', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
  {
    id: 'std-016',
    name: 'LEONARDO BORGES MEDEIROS',
    cpf: '671.209.431-77',
    registrationNumber: '06718294819',
    category: 'E',
    email: 'leonardo.medeiros@transportes.com',
    phone: '(61) 98110-9988',
    courseId: 'template-iet-qgex',
    courseName: 'Condutores de Veículos de Transporte de Emergência',
    periodStart: '08 de junho de 2026',
    periodEnd: '16 de junho de 2026',
    workload: '50h/a',
    issueDate: '18 de junho de 2026',
    certificateCode: '021/CVTE/2026',
    authHash: 'SHA-2C66A9E4D187',
    status: 'approved',
    emailSentStatus: 'pending',
    grades: [
      { discipline: 'Legislação de Trânsito', workload: '10h/a', grade: '9,5', instructor: 'PAULO DE JESUS CAMARGO' },
      { discipline: 'Direção Defensiva', workload: '15h/a', grade: '9,5', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
      { discipline: 'Primeiros Socorros e Atendimento Inicial', workload: '15h/a', grade: '10', instructor: 'FELIPE VILELA DA COSTA' },
      { discipline: 'Comportamento e Convívio Social', workload: '10h/a', grade: '10', instructor: 'ERIK ANDRE RODRIGUES SANTIAGO' },
    ],
  },
];

export function generateCryptoHash(seed: string): string {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0;
  }
  const hex = Math.abs(hash).toString(16).toUpperCase().padStart(8, '0');
  const randomSuffix = Math.floor(Math.random() * 0xffff).toString(16).toUpperCase().padStart(4, '0');
  return `SHA-${hex}${randomSuffix}`;
}
